apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: net
  annotations:
    github.com/project-slug: AlineGit/net
    backstage.io/techdocs-ref: value
spec:
  type: other
  lifecycle: unknown
  owner: aline
